#!/usr/bin/sh -e

UEVENT="/sys/class/power_supply/BAT${BLOCK_INSTANCE:-0}/uevent"

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[ ! -f "$UEVENT" ] && exit

. $UEVENT

PERCENT=$(echo "100 * $POWER_SUPPLY_ENERGY_NOW / $POWER_SUPPLY_ENERGY_FULL" | bc)
if [ $POWER_SUPPLY_POWER_NOW -eq 0 ]; then
    REMAINING="∞"
else
    REMAINING=$(date '+%R' -u -d '@'`expr 3600 \* $POWER_SUPPLY_ENERGY_NOW / $POWER_SUPPLY_POWER_NOW`)
fi

if [ $POWER_SUPPLY_STATUS = "Charging" ]; then
    GLYPH=
else
    if [ $PERCENT -le 10 ]; then
        GLYPH=""
    elif [ $PERCENT -le 35 ]; then
        GLYPH=""
    elif [ $PERCENT -le 65 ]; then
        GLYPH=""
    elif [ $PERCENT -le 90 ]; then
        GLYPH=""
    else
        GLYPH=""
    fi

    TWENTIES=$(echo "$PERCENT / 5" | bc)
    if [ $TWENTIES -eq 0 ]; then
        COLOR="#FF0000"
    elif [ $TWENTIES -eq 1 ]; then
        COLOR="#FFAE00"
    elif [ $TWENTIES -eq 2 ]; then
        COLOR="#FFF600"
    fi
    unset TWENTIES
fi

echo "$GLYPH $PERCENT% ($REMAINING)"
echo "$GLYPH $PERCENT% ($REMAINING)"
[ -n "$COLOR" ] && echo "$COLOR"
unset GLYPH
unset REMAINING
unset COLOR

if [ $PERCENT -le 10 ]; then
    exit 33
fi
