#!/usr/bin/env sh

INSTANCE=${BLOCK_INSTANCE:-0}
BAT_PATH="/sys/class/power_supply/BAT$INSTANCE"

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d "$BAT_PATH" ]] && exit

EN_NOW=$(< $BAT_PATH/energy_now)
EN_FULL=$(< $BAT_PATH/energy_full)
PW_NOW=$(< $BAT_PATH/power_now)
PERCENT=$(echo "100 * $EN_NOW / $EN_FULL" | bc)
if [ $PW_NOW -eq 0 ]; then
    REMAINING="∞"
else
    REMAINING=$(date '+%R' -u -d '@'`expr 3600 \* $EN_NOW / $PW_NOW`)
fi

if [ $(< $BAT_PATH/status) = "Charging" ]; then
    GLYPH=⚡
else
    if [ $PERCENT -le 10 ]; then
        GLYPH=""
    elif [ $PERCENT -le 35 ]; then
        GLYPH=""
    elif [ $PERCENT -le 65 ]; then
        GLYPH=""
    elif [ $QUARTERS -le 90 ]; then
        GLYPH=""
    else
        GLYPH=""
    fi

    TWENTIES=$(echo "$PERCENT / 5" | bc)
    if [ $TWENTIES -eq 0 ]; then
        COLOR="#FF0000"
    elif [ $TWENTIES -eq 1 ]; then
        COLOR="#FFAE00"
    elif [ $TWENTIES -eq 2 ]; then
        COLOR="#FFF600"
    fi
    unset TWENTIES
fi

echo "$GLYPH $PERCENT% ($REMAINING)"
echo "$GLYPH $PERCENT% ($REMAINING)"
echo $COLOR

