#!/usr/bin/sh -e

export $(sensors -u acpitz-virtual-0 | awk '/temp1_input:/{printf "TEMP=%d\n", $2}/temp1_crit:/{printf "CRIT=%d\n", $2}')

echo $TEMP ºC
echo $TEMP ºC

if [ $TEMP -gt $CRIT ]; then
    echo "#FF0000"
    exit 33
fi
