#!/usr/bin/env bash
declare -A status

check_status() {
    source $1/uevent
    if [ $RFKILL_STATE -eq 1 ]; then
        status[$RFKILL_TYPE]=1
    fi
    unset RFKILL_STATE
    unset RFKILL_TYPE
}

for device in /sys/class/rfkill/*; do
    check_status $device
done

declare -a output
if [ ${status[bluetooth]} -eq 1 ]; then
    output[${#output[@]}]=""
fi

if [ ${status[wlan]} -eq 1 ]; then
    output[${#output[@]}]=""
fi

if [ ${#output[@]} ]; then
    echo ${output[@]}
fi
