#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-$(awk '/^w/{ print $1; exit }' /proc/net/route)}"

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

ADDRESS=$(ifconfig $INTERFACE | awk '/inet/{ print $2; exit }')
QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
ESSID=$(iwconfig $INTERFACE | awk '/ESSID:/{ print substr($4, 8, length($4)-8)}')

#------------------------------------------------------------------------

echo "$ADDRESS ($QUALITY% @ $ESSID)" # full text
echo "$ADDRESS ($QUALITY% @ $ESSID)" # short text

# color
if [[ $QUALITY -ge 60 ]]; then
    echo "#00FF00"
elif [[ $QUALITY -ge 40 ]]; then
    echo "#FFF600"
elif [[ $QUALITY -ge 20 ]]; then
    echo "#FFAE00"
else
    echo "#FF0000"
fi
