#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-$(awk '/^w/{ print $1; exit }' /proc/net/route)}"

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(< /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

ADDRESS=$(ip a s $INTERFACE | awk '/inet/{ print substr($2, 1, length($2) - 3) }')
QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print $3 / 70 }')
ESSID=$(iw dev $INTERFACE link | awk '/SSID/{ print $2 }')

#------------------------------------------------------------------------

echo "$ESSID" # full text
echo "$QUALITY" | awk '{ printf "%d%%\n", int($0 * 100) }' # short text

if [[ -n $ADDRESS ]]; then
    echo $QUALITY | awk '{
        printf "#%.2X%.2X%.2X", sqrt(1 - $0) * 255, sqrt($0) * 255, 0
    }'
fi
