#!/usr/bin/sh -e

# geocode IP address
URL="ipinfo.io"
FORMAT="-?[\d\.]+,-?[\d\.]+"

# scrape coordinates from return JSON
read -r LAT LON <<EOF
$(curl -s "$URL" | grep -oP -- "$FORMAT" | tr ',' ' ')
EOF

# start xflux in daemon mode (forking)
exec "$(which xflux)" -l "$LAT" -g "$LON" "$@"
