#!/usr/bin/sh
hash xbacklight 2> /dev/null || exit

CONFIG="${HOME}/.config/backlight"

if [ $# -ne 0 ]; then
	xbacklight "$@"
elif [ -f "${CONFIG}" ]; then
	xbacklight -set "$(cat "$CONFIG")"
fi

xbacklight -get > "$CONFIG"
