#!/usr/bin/bash
# Add the following to "/etc/udev/rules.d/95-monitor-hotplug.rules":
# KERNEL=="card0", SUBSYSTEM=="drm", ENV{DISPLAY}=":0", ENV{XAUTHORITY}="/home/ranieri/.Xauthority", RUN+="/path/to/this/file"
# Don't forget to set the execute permission.

read VGA < /sys/class/drm/card0-VGA-1/status
read HDMI < /sys/class/drm/card0-HDMI-A-1/status
LID=$(awk '{print $2}' /proc/acpi/button/lid/LID/state)

flags=""

if [[ "x$LID" == "xclosed" ]]; then
	flags="${flags} --output LVDS-1 --off"
else
	flags="${flags} --output LVDS-1 --auto --primary"
fi

if [[ "x$VGA" == "xconnected" ]]; then
	if [[ "x$LID" == "xclosed" ]]; then
		flags="${flags} --output VGA-1 --auto --primary"
	else
		flags="${flags} --output VGA-1 --auto --left-of LVDS-1"
	fi
elif [[ "x$HDMI" == "xconnected" ]]; then
	if [[ "x$LID" == "xclosed" ]]; then
		flags="${flags} --output HDMI-1 --auto --primary"
	else
		flags="${flags} --output HDMI-1 --auto --left-of LVDS-1"
	fi
else
	flags="${flags} --output VGA-1 --off --output HDMI-1 --off"
fi

xrandr ${flags}
i3-msg -q reload
systemctl --user restart dunst.service nitrogen-restore.service polybar.service redshift.service xss-lock.service
