#!/usr/bin/bash
# Add the following to "/etc/udev/rules.d/95-monitor-hotplug.rules":
# KERNEL=="card0", SUBSYSTEM=="drm", ENV{DISPLAY}=":0", ENV{XAUTHORITY}="/home/ranieri/.Xauthority", RUN+="/path/to/this/file"
# Don't forget to set the execute permission.

read VGA < /sys/class/drm/card0-VGA-1/status

output="xrandr --output LVDS1 --auto"
if [[ "x$VGA" == "xconnected" ]]; then
  output="${output} --output VGA1 --auto --left-of LVDS1"
else
  output="${output} --output VGA1 --off"
fi

${output}
i3-msg -q reload
[[ -x /usr/bin/nitrogen ]] && nitrogen --restore
killall -q -USR1 conky
