#!/usr/bin/env sh
FACTOR=${FACTOR:-$((`date +%m` + `date +%h` * 60))}
MINIMUM=${MINIMUM:-10}

# beyond 6:30 to 18:30, don't check and use night factor
if [[ $FACTOR -lt 390 || $FACTOR -gt 1110 ]]; then
    echo $MINIMUM
else
    # will vary between
    echo "scale=2;$MINIMUM + ($FACTOR - 390) / 4" | bc
fi
