#!/usr/bin/env bash
IMAGE=$(mktemp --suffix=".png")

HW=$(xrandr -q | awk '/Screen 0/{printf "%dx%d", $8, $10}')

[ -d /tmp/lockr ] || mkdir -p /tmp/lockr
# if [ ! -f "/tmp/lockr/$HW.png" ]; then
    SHRINK="-sample 50% -blur 0x4"
    # BLUR="-blur -0x5"
    # STRETCH="-sample 400% -blur 0x1"
    STRETCH="-magnify -blur 0x1"
    SCALE="-scale $HW^ -gravity center -extent $HW"
    # ICON="${HOME}/.config/lock.png -gravity center -composite"

    playerctl pause && volctrl mute && pkill -RTMIN+1 i3blocks
    # maim -f jpg -m 3 -u | convert - ${SHRINK} ${BLUR} ${STRETCH} ${ICON} png:- | i3lock -n -i /dev/stdin
    convert "$(cat $HOME/.cache/wal/wal)" ${SHRINK} ${STRETCH} ${SCALE} $IMAGE
# fi

i3lock -n -i $IMAGE
