#!/usr/bin/env sh
ICON="${HOME}/.config/lock.png"
IMAGE=$(mktemp --suffix=".png")
maim --format png /dev/stdout | convert - -blur 2x8 "$ICON" -gravity center -composite "$IMAGE"

i3lock -i "$IMAGE" -n
rm "$IMAGE"
