#!/usr/bin/env bash
INPUT="/tmp/.locked.png"
[ ! -f "$INPUT" ] && hotplug $(< ~/.cache/wal/wal)

if [ -z "$SWAYSOCK" ]; then
    LOCKER="i3lock -n"
    # TODO: grab the largest screen
    RESOLUTION=$(xrandr -q | awk '/Screen 0/{printf "%dx%d", $8, $10}')

    # i3lock doesn't autoscale image, sux ballz
    SCALE="-scale $RESOLUTION^ -gravity center -extent $RESOLUTION"
else
    LOCKER="swaylock"
    RESOLUTION=$(swaymsg -t get_outputs | jq -r 'max_by(.rect.width).rect | "\(.width)x\(.height)"')
fi

$LOCKER -i $INPUT
