#!/usr/bin/env sh
arg=$1
shift

case $arg in
    -c)
        maim $@ -f png -u /dev/stdout | xclip -t image/png;;
    -p)
        maim $@ -f png -u "$HOME/Pictures/Screenshots/$(date +%F-%T).png";;
esac
